import cv2
from fer import FER
import operator

def analyze_clip_emotion(clip_path: str) -> str:
    """
    Analyzes a video clip to determine the dominant emotion.

    Args:
        clip_path: The file path to the video clip.

    Returns:
        The dominant emotion (e.g., 'happy', 'sad', 'angry') or 'neutral' if no
        strong emotion is detected.
    """
    try:
        # Initialize the emotion detector
        detector = FER(mtcnn=True)

        # Open the video file
        cap = cv2.VideoCapture(clip_path)
        if not cap.isOpened():
            print(f"Error: Could not open video file {clip_path}")
            return "unknown"

        # Store emotion scores from all frames
        total_emotions = {
            'angry': 0, 'disgust': 0, 'fear': 0, 'happy': 0,
            'sad': 0, 'surprise': 0, 'neutral': 0
        }
        frame_count = 0

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            # Analyze emotions in the frame
            # The detector returns a list of faces, each with an emotion dict
            emotions_in_frame = detector.detect_emotions(frame)

            # We'll focus on the first detected face for simplicity
            if emotions_in_frame:
                face_emotions = emotions_in_frame[0]['emotions']
                for emotion, score in face_emotions.items():
                    if score > 0:  # Only add emotions with a positive score
                        total_emotions[emotion] += score
                frame_count += 1

        cap.release()

        if frame_count == 0:
            print(f"No faces detected in {clip_path}")
            return "neutral"

        # Find the dominant emotion across all frames
        # We ignore 'neutral' unless it's the only option
        non_neutral_emotions = {k: v for k, v in total_emotions.items() if k != 'neutral'}

        if any(non_neutral_emotions.values()):
            dominant_emotion = max(non_neutral_emotions.items(), key=operator.itemgetter(1))[0]
        else:
            dominant_emotion = "neutral"

        print(f"Dominant emotion for {clip_path}: {dominant_emotion}")
        return dominant_emotion

    except Exception as e:
        print(f"An error occurred during emotion analysis for {clip_path}: {e}")
        return "unknown"

if __name__ == '__main__':
    # NOTE: This test block requires a video clip file to work.
    # Due to the ffmpeg issue in this environment, we cannot reliably generate
    # a clip for testing. The following shows how it would be tested.

    print("Running AI Emotion Analysis Test...")

    # In a real test, we would point this to a clip generated by video_processing.py
    # e.g., test_clip_path = "video_creator/temp/clips/dQw4w9WgXcQ/clip_0000_0003.mp4"
    test_clip_path = "path/to/your/test_clip.mp4"

    if not cv2.VideoCapture(test_clip_path).isOpened():
         print(f"\nWARNING: Test cannot run. Please provide a valid video clip at '{test_clip_path}'.")
    else:
        emotion = analyze_clip_emotion(test_clip_path)
        print(f"\nTest result: The dominant emotion is '{emotion}'.")